---
title: "NO2 Exploratory Analysis"
author: "Alana Schreibman"
date: "6/9/2021"
output: 
  html_document:
    toc: true
    toc_float: 
        collapsed: true
        smooth_scroll: true
    depth: 3 
    theme: cosmo
    highlight: pygments
---

```{r global options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

#Load libraries needed.  
``` {r, eval = FALSE}
library(raster)
library(sf)
library(rgdal)
library(ggplot2)
library(tidyr)
library(dplyr)
library(tidyverse)
```

#Earth Engine API setup. 
``` {r, eval = FALSE}
install.packages("reticulate")
install.packages("R6")
install.packages("processx")
install.packages("rgee")
install.packages("geojsonio")
library(mapview)
library(remotes)
library(reticulate)
library(rgee)
install_github("r-spatial/rgee")
ee_install(py_env = "rgee")
ee_install()
ee_Initialize()
ee_install_upgrade()
py_install("geemap")
gm <- import("geemap")
```


#Experimenting with Earth Engine.
```{r, eval = TRUE}
ee_Initialize()

# Successful: Selecting an image from ee$ImageCollection. 
col.NO2<-ee$ImageCollection('COPERNICUS/S5P/NRTI/L3_NO2')
start <- ee$Date("2020-03-26")
end <- ee$Date("2021-06-07")
filter<-col$filterDate(start,end) %>%
  ee$ImageCollection$mean()
ee_print(img,clear=TRUE)

#Get more information using cat:
bandNames<-img$bandNames()
cat("Bands: ",paste(bandNames$getInfo(),"\n",collapse=" "))

b1proj<- img$select('NO2_column_number_density')$projection()
cat("B1 projection: ", paste(b1proj$getInfo(),"\n", collapse = "
"))

b1scale<-img$select('NO2_column_number_density')$projection()$nominalScale()
cat("B1 Scale: ", paste(b1scale$getInfo(),"\n", collapse = " "))

Map$setCenter(65.27,24.11, zoom = 4)
Map$addLayer(filter,visParams=list(bands = "NO2_column_number_density", min = 0,max = 0.0002, palette = c("black", "blue", "purple", "cyan", "green", "yellow", "red"), opacity=0.4), "True Color Image")
```

```{r, eval = TRUE}
#Can't figure out the problem here: seems like map generated is empty.
blocks <- ee$ImageCollection("COPERNICUS/S5P/NRTI/L3_NO2")
start <- ee$Date("2019-07-11")
end <- ee$Date("2019-07-20")
subset <- blocks$filterDate(start,end)
image <- subset$first()
image
sf_subset <- ee_as_sf(x = image)
no2viz <- list(
        min = 0,
        max = .0002,
        bands = "NO2_column_number_density",
        palette = c("black", "blue", "purple", "cyan", "green", "yellow", "red")
)
Map$addLayer(image, no2viz,'NO2')
```

```{r, eval = TRUE}
#Attempt to download and use raster commands. Commands seem to work; problem is that only small regions can be downloaded at a time because there are too many pixels.
#loading the image to be downloaded

#Downloading file of the US.
image1 <- ee$ImageCollection("COPERNICUS/S5P/NRTI/L3_NO2")$filterDate('2018-06-26', '2020-06-26')$select("NO2_column_number_density") %>%
   ee$ImageCollection$mean()
geometry <- ee$Geometry$Rectangle(
  coords = c(-170, 18, -56, 71))
geom_params <- list(
 crs = 'EPSG:4326',
 region = geometry,
 maxPixels = 1E9
)
path <- image1$getDownloadUrl(geom_params)
print(path)


image1 <- ee$ImageCollection("COPERNICUS/S5P/NRTI/L3_NO2")$filterDate('2020-01-01', '2020-04-01')$select("NO2_column_number_density")$median()
geom_params <- list(
 crs = 'EPSG:4326',
 maxPixels = 1E9
)
path <- image1$getDownloadUrl(geom_params)
print(path)

thermal <- stack('download.NO2_column_number_density.tif')
plotRGB(thermal,stretch='lin')
visible<-stack('download.NO2_column_number_density.tif')
plotRGB(visible,stretch='lin')

fn <- "download.NO2_column_number_density.tif"
r1 <- raster(fn)
plot(r1, col = terrain.colors(4))
```

```{r, eval = TRUE}
#Goal: Filter the dataset by dates, reproject and select only the band "NO2_column_number_density". Get a time series plot of NO2 values. 
#Problem here: "request payload size exceeds the limit: 10485760 bytes" error message. 
NO2 <- ee$ImageCollection("COPERNICUS/S5P/NRTI/L3_NO2")$
  filterDate("2019-04-01","2020-04-01")$
  map(function(x) x$reproject("EPSG:4326")$select("NO2_column_number_density"))
world.sf <- st_read("world_maps/country_gen_trim.shp")  # Read shapefile as an sf object
world.geo <- st_geometry(world.sf)

ee__NO2 <- ee_extract(NO2, world.geo, sf = FALSE)
colnames(ee_NO2) <- sprintf("%02d", 1:12)
ee_NO2$name <- nc$NAME

ee_NO2 %>%
  pivot_longer(-name, names_to = "month",values_to = "NO2_column_number_density")%>%
  ggplot(aes(x = month, y = NO2_column_number_density, group = name, color = NO2_column_number_density)) +
      geom_line(alpha = 0.4)+
      xlab("Month") +
      ylab("NO2 Concentration") +
      theme_minimal()
```


```{r, eval = TRUE}
#Goal is to compute trend in NO2 levels over the years and perform a linear fit. Problem: output map seems empty. 
createTimeBand <-function(img) {
  year <- ee$Date(img$get('system:time_start'))$get('year')$subtract(2018L)
  ee$Image(year)$byte()$addBands(img)
}
collection <- ee$
  ImageCollection('COPERNICUS/S5P/NRTI/L3_NO2')$
  select('NO2_column_number_density')$
  map(createTimeBand)
col_reduce <- collection$reduce(ee$Reducer$linearFit())
col_reduce <- col_reduce$addBands(
  col_reduce$select('scale'))
ee_print(col_reduce)
Map$setCenter(9.08203, 47.39835, 3)
Map$addLayer(
  eeObject = col_reduce,
  visParams = list(
    bands = c("scale", "offset", "scale"),
    min = 0,
    max = c(0.5, 5, -0.5)
  ),
  name = "NO2 trend"
)
```

```{r, eval = TRUE}
#Successful: world map of NO2 concentrations filtered into colored zones. March-May 2019.
NO2img <- ee$ImageCollection("COPERNICUS/S5P/NRTI/L3_NO2")$filterDate('2019-03-26', '2019-05-26')$select("NO2_column_number_density") %>%
  ee$ImageCollection$mean()
pal<-c('#ffffb2','#fecc5c','#fd8d3c','#f03b20','#bd0026')
Map$setCenter(2.373,48.8683,3)
map.zones<-NO2img$expression("(b('NO2_column_number_density') > 0.00015) ? 4 : (b('NO2_column_number_density') > 0.000125) ? 3 : (b('NO2_column_number_density') > 0.0001) ? 2 : (b('NO2_column_number_density') > 0.00007) ? 1 : 0"
)
Map$addLayer(map.zones,list(min=0,max=4,palette=pal,opacity=0.4),
 'NO2 concentration')
```

```{r, eval = TRUE}
#Successful: world map of NO2 concentrations filtered into colored zones. March-May 2020.
NO2img <- ee$ImageCollection("COPERNICUS/S5P/NRTI/L3_NO2")$filterDate('2020-03-26', '2020-05-26')$select("NO2_column_number_density") %>%
  ee$ImageCollection$mean()
pal<-c('#ffffb2','#fecc5c','#fd8d3c','#f03b20','#bd0026')
Map$setCenter(2.373,48.8683,3)
map.zones<-NO2img$expression("(b('NO2_column_number_density') > 0.00015) ? 4 : (b('NO2_column_number_density') > 0.000125) ? 3 : (b('NO2_column_number_density') > 0.0001) ? 2 : (b('NO2_column_number_density') > 0.00007) ? 1 : 0"
)
Map$addLayer(map.zones,list(min=0,max=4,palette=pal,opacity=0.4),
 'NO2 concentration')
```

```{r, eval = TRUE}
#Successful: world map of population filtered into colored zones.
col.pop.den <- ee$ImageCollection("WorldPop/GP/100m/pop")$select("population") %>%
  ee$ImageCollection$mean()
pal<-c('#ffffb2','#fecc5c','#fd8d3c','#f03b20','#bd0026')
Map$setCenter(2.373,48.8683,3)
map.zones<-pop.den$expression("(b('population') > 40) ? 4 : (b('population') > 35) ? 3 : (b('population') > 25) ? 2 : (b('population') > 15) ? 1 : 0"
)
Map$addLayer(map.zones,list(min=0,max=4,palette=pal,opacity=0.4),
 'population density')
```


